=== gabbrielcast/BancoGS/p5.1/validacion.dtd
<!ELEMENT discografica (cancion*)>
<!ELEMENT cancion (titulo,compositores,disco,sello,artistas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor*)>
<!ELEMENT compositor (nombre,apellidos?)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT disco (nombre)>
<!ELEMENT sello (nombre)>
<!ELEMENT artistas (artista*)>
<!ELEMENT artista (nombre)>
<!ELEMENT nombre (#PCDATA)>

<!ATTLIST cancion duracion CDATA #IMPLIED
          anno CDATA  #REQUIRED>

=== gabbrielcast/BancoGS/p5.1/Part1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cancion SYSTEM "validacion.dtd">
<cancion duracion="4:08" anno="1979">

    <titulo>Video Killed the Radio Star</titulo>
    <compositores>
        <compositor>
            <nombre>Geoff</nombre>
            <apellidos>Downes</apellidos>
        </compositor>

        <compositor>
            <nombre>Trevor</nombre>
            <apellidos>Horn</apellidos>
        </compositor>

        <compositor>
            <nombre>Bruce</nombre>
            <apellidos>Woolley</apellidos>
        </compositor>

    </compositores>

    <disco>
        <nombre>The Age of Plastic</nombre>
    </disco>

    <sello>
        <nombre>Island</nombre>
    </sello>

    <artistas>
        <artista>
            <nombre>Buggles</nombre>
        </artista>
    </artistas>

</cancion>
